PARAMS = {'exp1': {'MAX_LEN': 100,
          'MIN_FREQ': 10,
          'EMBEDDING_SIZE': 32,
          'CONTEXT_WINDOW': 5,
          'TEST_SIZE': .2,
          'SEED': 41,
          'LEARNING_RATE': 0.01,
          'NB_EPOCHS': 3,
          'BATCH_SIZE': 512,
          'WORD_DROPOUT': 0.
        },
        'exp2': {'MAX_LEN': 100,
          'MIN_FREQ': 10,
          'EMBEDDING_SIZE': 128,
          'CONTEXT_WINDOW': 5,
          'TEST_SIZE': .2,
          'SEED': 41,
          'LEARNING_RATE': 0.001,
          'NB_EPOCHS': 10,
          'BATCH_SIZE': 512,
          'WORD_DROPOUT': 0.,
        },
        'exp3': {'MAX_LEN': 200,
          'MIN_FREQ': 5,
          'EMBEDDING_SIZE': 300,
          'CONTEXT_WINDOW': 5,
          'TEST_SIZE': .2,
          'SEED': 41,
          'LEARNING_RATE': 0.01,
          'NB_EPOCHS': 4,
          'BATCH_SIZE': 512,
          'WORD_DROPOUT': 0.01,
        },
        'exp4': {'MAX_LEN': 200,
          'MIN_FREQ': 5,
          'EMBEDDING_SIZE': 300,
          'CONTEXT_WINDOW': 5,
          'TEST_SIZE': .2,
          'SEED': 41,
          'LEARNING_RATE': 0.01,
          'NB_EPOCHS': 4,
          'BATCH_SIZE': 512,
          'WORD_DROPOUT': 0.01,
        },
        'exp5': {'MAX_LEN': 200,
          'MIN_FREQ': 3,
          'EMBEDDING_SIZE': 300,
          'CONTEXT_WINDOW': 5,
          'TEST_SIZE': .2,
          'SEED': 41,
          'LEARNING_RATE': 0.001,
          'NB_EPOCHS': 7,
          'BATCH_SIZE': 512,
          'WORD_DROPOUT': 0.001,
        },
        'exp6': {'MAX_LEN': 200,
          'MIN_FREQ': 10,
          'EMBEDDING_SIZE': 300,
          'CONTEXT_WINDOW': 5,
          'TEST_SIZE': .2,
          'SEED': 41,
          'LEARNING_RATE': 0.001,
          'NB_EPOCHS': 4,
          'BATCH_SIZE': 512,
          'WORD_DROPOUT': 0.1,
        },
        'exp7': {'MAX_LEN': 200,
          'MIN_FREQ': 10,
          'TEST_SIZE': .2,
          'SEED': 41,
          'LEARNING_RATE': 0.001,
          'NB_EPOCHS': 4,
          'BATCH_SIZE': 512,
          'WORD_DROPOUT': 0.1,
        }
        }
