MIN_COUNT       = 5
WINDOW_SIZE     = 2
LEARNING_RATE   = .025
BTT_LEARNING_RATE = 0.05
FT_LEARNING_RATE = .001
LOGGING_STEPS   = 1000
NUM_SKIPS       = 2
BATCH_SIZE      = 2 ** 2
BTT_BATCH_SIZE  = 2 ** 7
FT_BATCH_SIZE   = 2 ** 2
EMBEDDING_SIZE  = 32
WORD            = 'civilization'
SAMPLE          = 1000
PROJECTION_FILE = '../../references/tsne_projection.png'
NUM_NEG_WORDS   = 5
UNIGRAM_POWER   = (3 / 4)
NGRAM_RANGE     = 3
EPOCHS          = 25
