MIN_COUNT       = 5
WINDOW_SIZE     = 2
LEARNING_RATE   = .025
LOGGING_STEPS   = 1000
NUM_SKIPS       = 2
BATCH_SIZE      = 2 ** 2
EMBEDDING_SIZE  = 32
WORD            = 'eight'
SAMPLE          = 1000
PROJECTION_FILE = '../../references/tsne_projection.png'
NUM_NEG_WORDS   = 5
UNIGRAM_POWER   = (3 / 4)
